---
- name: Ensure crontab package is installed
  ansible.builtin.package:
    name: cron
    state: present
  tags: cron

- name: Create a directory if it does not exist
  become_user: "{{ ansible_user }}"
  become: false
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/cronjobs
    state: directory
    mode: '0755'
  tags: cron

- name: write bash command for auto update
  become_user: "{{ ansible_user }}"
  become: false
  ansible.builtin.shell: |
    echo "sudo apt update && sudo apt upgrade -y" > /home/{{ ansible_user }}/cronjobs/update.sh
    chmod +x /home/{{ ansible_user }}/cronjobs/update.sh
  args:
    creates: /home/{{ ansible_user }}/cronjobs/update.sh
  tags: cron

- name: Create cron for auto update
  ansible.builtin.cron:
    name: "Auto update/upgrade via apt"
    minute: '30'
    hour: '05'
    month: '*'
    day: '*'
    weekday: '0'
    job: "/bin/bash /home/{{ ansible_user }}/cronjobs/update.sh"
    user: "{{ ansible_user }}"
  tags: cron

- name: Add custom cronjobs
  become: true
  ansible.builtin.cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    month: "{{ item.month }}"
    day: "{{ item.day }}"
    weekday: "{{ item.weekday }}"
    job: "{{ item.job }}"
    user: "{{ item.user }}"
  loop: "{{ my_crons }}"
  when:
    - my_crons is defined
    - my_crons | length > 0
  tags: cron
